export interface MdStyle {
  name: string;
  label: string;
  vars: Record<string, string>;
}

export const mdStyles: MdStyle[] = [
  {
    name: "default",
    label: "默认",
    vars: {
      "--md-heading-font": "inherit",
      "--md-heading-weight": "600",
      "--md-heading-decoration": "none",
      "--md-h1-size": "1.8em",
      "--md-h1-border": "1px solid var(--border)",
      "--md-h2-size": "1.5em",
      "--md-h2-border": "1px solid var(--border)",
      "--md-h3-size": "1.25em",
      "--md-h4-size": "1.1em",
      "--md-h-color": "var(--text-heading)",
      "--md-h-line-height": "1.3",
      "--md-block-border": "4px solid var(--blockquote-border)",
      "--md-block-bg": "rgba(0, 122, 204, 0.05)",
      "--md-block-color": "var(--blockquote-text)",
      "--md-block-radius": "0 4px 4px 0",
      "--md-code-font": "var(--font-mono)",
      "--md-code-bg": "var(--code-bg)",
      "--md-code-border": "1px solid var(--border)",
      "--md-code-radius": "6px",
      "--md-inline-code-bg": "var(--inline-code-bg)",
      "--md-inline-code-radius": "4px",
      "--md-hr-style": "1px solid var(--border)",
      "--md-p-size": "15px",
      "--md-p-line-height": "1.7",
      "--md-list-style": "disc",
      "--md-table-stripe": "var(--table-row-alt)",
    },
  },
  {
    name: "elegant",
    label: "优雅",
    vars: {
      "--md-heading-font": "'Georgia', 'Times New Roman', serif",
      "--md-heading-weight": "700",
      "--md-heading-decoration": "none",
      "--md-h1-size": "2em",
      "--md-h1-border": "none",
      "--md-h2-size": "1.6em",
      "--md-h2-border": "2px solid var(--accent)",
      "--md-h3-size": "1.3em",
      "--md-h4-size": "1.1em",
      "--md-h-color": "var(--text-heading)",
      "--md-h-line-height": "1.4",
      "--md-block-border": "3px double var(--accent)",
      "--md-block-bg": "rgba(0, 122, 204, 0.03)",
      "--md-block-color": "var(--text-secondary)",
      "--md-block-radius": "0",
      "--md-code-font": "'Georgia', serif",
      "--md-code-bg": "var(--bg-tertiary)",
      "--md-code-border": "1px solid var(--border)",
      "--md-code-radius": "4px",
      "--md-inline-code-bg": "var(--bg-tertiary)",
      "--md-inline-code-radius": "3px",
      "--md-hr-style": "none",
      "--md-p-size": "16px",
      "--md-p-line-height": "1.8",
      "--md-list-style": "disc",
      "--md-table-stripe": "var(--bg-tertiary)",
    },
  },
  {
    name: "modern",
    label: "现代",
    vars: {
      "--md-heading-font": "var(--font-sans)",
      "--md-heading-weight": "800",
      "--md-heading-decoration": "none",
      "--md-h1-size": "2.2em",
      "--md-h1-border": "none",
      "--md-h2-size": "1.7em",
      "--md-h2-border": "none",
      "--md-h3-size": "1.3em",
      "--md-h4-size": "1.1em",
      "--md-h-color": "var(--accent)",
      "--md-h-line-height": "1.2",
      "--md-block-border": "none",
      "--md-block-bg": "var(--bg-tertiary)",
      "--md-block-color": "var(--text-secondary)",
      "--md-block-radius": "8px",
      "--md-code-font": "'Fira Code', 'Cascadia Code', monospace",
      "--md-code-bg": "var(--bg-tertiary)",
      "--md-code-border": "none",
      "--md-code-radius": "8px",
      "--md-inline-code-bg": "var(--bg-tertiary)",
      "--md-inline-code-radius": "4px",
      "--md-hr-style": "2px dashed var(--border)",
      "--md-p-size": "15px",
      "--md-p-line-height": "1.7",
      "--md-list-style": "none",
      "--md-table-stripe": "var(--bg-tertiary)",
    },
  },
  {
    name: "compact",
    label: "紧凑",
    vars: {
      "--md-heading-font": "var(--font-sans)",
      "--md-heading-weight": "700",
      "--md-heading-decoration": "none",
      "--md-h1-size": "1.5em",
      "--md-h1-border": "none",
      "--md-h2-size": "1.3em",
      "--md-h2-border": "none",
      "--md-h3-size": "1.1em",
      "--md-h4-size": "1em",
      "--md-h-color": "var(--text-heading)",
      "--md-h-line-height": "1.2",
      "--md-block-border": "2px solid var(--border)",
      "--md-block-bg": "transparent",
      "--md-block-color": "var(--text-secondary)",
      "--md-block-radius": "0",
      "--md-code-font": "var(--font-mono)",
      "--md-code-bg": "var(--bg-primary)",
      "--md-code-border": "1px solid var(--border)",
      "--md-code-radius": "0",
      "--md-inline-code-bg": "var(--bg-tertiary)",
      "--md-inline-code-radius": "2px",
      "--md-hr-style": "1px solid var(--border)",
      "--md-p-size": "13px",
      "--md-p-line-height": "1.5",
      "--md-list-style": "disc",
      "--md-table-stripe": "var(--bg-tertiary)",
    },
  },
  {
    name: "serif",
    label: "报刊",
    vars: {
      "--md-heading-font": "'Georgia', 'Noto Serif CJK SC', serif",
      "--md-heading-weight": "700",
      "--md-heading-decoration": "none",
      "--md-h1-size": "2.4em",
      "--md-h1-border": "3px double currentColor",
      "--md-h2-size": "1.8em",
      "--md-h2-border": "1px solid currentColor",
      "--md-h3-size": "1.4em",
      "--md-h4-size": "1.2em",
      "--md-h-color": "var(--text-heading)",
      "--md-h-line-height": "1.3",
      "--md-block-border": "none",
      "--md-block-bg": "var(--bg-secondary)",
      "--md-block-color": "var(--text-secondary)",
      "--md-block-radius": "0",
      "--md-code-font": "'Courier New', monospace",
      "--md-code-bg": "var(--bg-secondary)",
      "--md-code-border": "1px solid var(--border)",
      "--md-code-radius": "0",
      "--md-inline-code-bg": "var(--bg-secondary)",
      "--md-inline-code-radius": "0",
      "--md-hr-style": "3px double var(--border)",
      "--md-p-size": "16px",
      "--md-p-line-height": "1.9",
      "--md-list-style": "disc",
      "--md-table-stripe": "var(--bg-secondary)",
    },
  },
  {
    name: "handwritten",
    label: "手写",
    vars: {
      "--md-heading-font": "'Segoe Print', 'Comic Sans MS', cursive",
      "--md-heading-weight": "bold",
      "--md-heading-decoration": "none",
      "--md-h1-size": "2em",
      "--md-h1-border": "none",
      "--md-h2-size": "1.6em",
      "--md-h2-border": "none",
      "--md-h3-size": "1.3em",
      "--md-h4-size": "1.1em",
      "--md-h-color": "var(--text-heading)",
      "--md-h-line-height": "1.4",
      "--md-block-border": "3px solid var(--accent)",
      "--md-block-bg": "rgba(0, 122, 204, 0.04)",
      "--md-block-color": "var(--text-secondary)",
      "--md-block-radius": "8px",
      "--md-code-font": "'Courier New', monospace",
      "--md-code-bg": "var(--bg-secondary)",
      "--md-code-border": "2px dashed var(--border)",
      "--md-code-radius": "12px",
      "--md-inline-code-bg": "var(--bg-tertiary)",
      "--md-inline-code-radius": "6px",
      "--md-hr-style": "2px dotted var(--border)",
      "--md-p-size": "16px",
      "--md-p-line-height": "2",
      "--md-list-style": "circle",
      "--md-table-stripe": "var(--bg-secondary)",
    },
  },
  {
    name: "terminal",
    label: "终端",
    vars: {
      "--md-heading-font": "var(--font-mono)",
      "--md-heading-weight": "bold",
      "--md-heading-decoration": "none",
      "--md-h1-size": "1.6em",
      "--md-h1-border": "none",
      "--md-h2-size": "1.4em",
      "--md-h2-border": "none",
      "--md-h3-size": "1.2em",
      "--md-h4-size": "1.1em",
      "--md-h-color": "var(--accent)",
      "--md-h-line-height": "1.2",
      "--md-block-border": "1px solid var(--accent)",
      "--md-block-bg": "var(--bg-primary)",
      "--md-block-color": "var(--accent)",
      "--md-block-radius": "0",
      "--md-code-font": "var(--font-mono)",
      "--md-code-bg": "var(--bg-primary)",
      "--md-code-border": "1px solid var(--accent)",
      "--md-code-radius": "0",
      "--md-inline-code-bg": "var(--bg-primary)",
      "--md-inline-code-radius": "0",
      "--md-hr-style": "1px dashed var(--accent)",
      "--md-p-size": "14px",
      "--md-p-line-height": "1.6",
      "--md-list-style": "disc",
      "--md-table-stripe": "var(--bg-primary)",
    },
  },
];
